-- phpMyAdmin SQL Dump
-- version 5.2.0
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Waktu pembuatan: 11 Des 2023 pada 10.22
-- Versi server: 10.4.24-MariaDB
-- Versi PHP: 7.4.29

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `project-iir`
--

-- --------------------------------------------------------

--
-- Struktur dari tabel `articles`
--

CREATE TABLE `articles` (
  `id` bigint(20) UNSIGNED NOT NULL,
  `title` varchar(255) DEFAULT NULL,
  `citations` int(11) DEFAULT NULL,
  `author` varchar(255) DEFAULT NULL,
  `abstract` longtext DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

--
-- Dumping data untuk tabel `articles`
--

INSERT INTO `articles` (`id`, `title`, `citations`, `author`, `abstract`) VALUES
(1, 'Tinjauan Pustaka Sistematis: Perkembangan Metode Peramalan Harga Emas', 3, 'Sasmi Hidayatul Yulianing Tyas', 'Prediksi harga emas merupakan hal yang menantang untuk diteliti karena harga emas bersifat fluktuatif. Selain itu, emas juga menjadi alat investasi utama urutan ketiga berdasarkan laporan survei pasar ritel emas tahun 2019. Oleh karena itu kebutuhan emas selalu meningkat 15% setiap tahunnya. Hal ini menjadi pemicu bagi berkembangnya berbagai metode peramalan emas. Pada penelitian ini akan dilakukan tinjauan pustaka sistematis untuk mengidentifikasi perkembangan metode peramalan harga emas. Metode yang digunakan adalah Systematic Literature Review dan dihasilkan sebanyak 28 artikel ilmiah untuk direview. Berdasarkan analisis diketahui bahwa sebagian besar metode yang digunakan adalah berbasis deep learning. Metrik performa metode yang digunakan pada mayoritas literatur adalah RMSE dan MAE. Sedangkan data set yang digunakan adalah data keuangan seperti harga emas?&#8230;'),
(2, 'Overconfident Behavior in a Security Market, the Implication of Self Deceptive Behavior in Price Discovery Processes&#8211;a Market Experiment', 4, 'Mahatma Kufepaksi', 'People may suffer from overconfidence in their daily activities. According to psychological research, less informed individuals may suffer from overconfidence. Empirical research shows that investors suffer from transaction losses due to overconfidence. This current research is an experimental research project that addresses these issues. According to the research design, all investors are classified into three groups based on their scores of overconfidence, namely the less informed investors, the rational (average) investors, and the more informed investors. In order to observe the responses of the groups of investors when they receive valuable information, the research employs four different types of treatments consisting of the condition of no market information, the provision of guidance of security prediction, the good news and the bad news.  The research demonstrates that the less informed investors are inclined to assess the precision of their knowledge and information excessively so that they produce a higher mean of prediction and price errors than those of the more informed investors in all experimental market sessions, except in the market session of good news. The phenomenon indicates that less informed investors conduct a self deceptive behavior. The result of the research also shows that although the less informed investors have higher mean of prediction or price errors, they have a chance to gain profit as long as they are able to deliver the predicted value of the security accurately which is closer to the market price that reflects the expected price of the majority of the market players.  Keywords: Overconfidence, self-deception, price?&#8230;'),
(3, 'Magic Formula: Sebuah Tinjauan dalam Prediksi Perusahaan-Perusahaan Unggulan di Indonesia', 2, 'Ni Luh Putu Uttari Premananda, Md Yudyantara Risadi', 'Purpose: This study aimed at investigating the performance of a value investing strategy called the &#8220;Magic Formula&#8221;, introduced by Joel Greenblatt (2006), applied to the Indonesian Stock Exchange. Magic Formula is a simple stock selection strategy by ranking stocks based on calculating Return on Capital and Earnings Yield.'),
(4, 'Prediksi harga saham menggunakan support vector regression dengan algoritma grid search', 60, 'Hasbi Yasin, Alan Prahutama, Tiani Wahyu Utami', 'The stock market has become a popular investment channel in recent years because of the low return rates of other investment. The stock price prediction is in the interest of both private and institution investors. Accurate forecasting of stock prices is an appealing yet difficult activity in the business world. Therefore, stock prices forecasting is regarded as one of the most challenging topics in business. The forecasting techniques used in the literature can be classified into two categories: linear models and non linear models. One of forecasting techniques in nonlinear models is support vector regression (SVR). Basically, SVR adopts the structural risk minimization principle to estimate a function by minimizing an upper bound of the generalization. The optimal parameters of SVR can be use Grid Search Algorithm method. Concept of this method is using cross validation (CV). In this paper, the SVR model use linear kernel function. The accurate prediction of stock price, in telecommunication, is 92.47% for training data and 83.39% for testing data.'),
(5, 'Prediksi harga saham PT. BRI, TBK. Menggunakan metode ARIMA (autoregressive integrated moving average)', 28, 'Greis S Lilipaly, Djoni Hatidja, John S Kekenusa', 'Metode ARIMA adalah salah satu metode yang dapat digunakan dalam memprediksi perubahan harga saham. Tujuan dari penelitian ini adalah untuk membuat model ARIMA dan memprediksi harga saham PT. BRI, Tbk. bulan November 2014. Penelitian menggunakan data harga saham? harian? maksimum dan minimum PT. BRI, Tbk. Data yang digunakan yaitu data sekunder yang diambil dari website perusahaan PT. BRI, Tbk. sejak 3 Januari 2011 sampai 20 Oktober 2014 untuk memprediksi harga saham bulan November 2014. Dari hasil penelitian menunjukkan bahwa data tahun 2011 sampai Oktober 2014 bisa digunakan untuk memprediksi harga saham bulan November 2014. Hasilnya model ARIMA untuk harga saham maksimum adalah ARIMA (2, 1, 3) dan harga saham minimum adalah model (2, 1, 3) yang dapat digunakan untuk memprediksi data bulan November 2014 dengan validasi prediksi yang diambil pada bulan Oktober 2014 untuk selanjutnya dilakukan prediksi bulan November 2014.'),
(6, 'Perbandingan Prediksi Harga Saham dengan model ARIMA dan Artificial Neural Network', 28, 'Bagas Yafitra Pandji, Indwiarti Indwiarti, Aniq Atiqi Rohmawati', 'Kondisi perekonomian dunia mengalami perubahan yang signifikan, mayoritas merupakan dampak dari kenaikan minyak dunia, karena minyak merupakan sumber energi utama di dunia. Kondisi tersebut juga berimbas pada harga saham di pasar modal. Ada beberapa variabel yang mempengaruhi nilai return saham, yang sifatnya linier dan non-linier terhadap return harga saham. Untuk memodelkan observasi yang linier digunakan model time series Autoregressive Moving Average (ARIMA). Selanjutnya, untuk observasi yang non-linier digunakan Artificial Neural Network (ANN). Pada penelitian ini didapatkan perbandingan hasil perhitungan error RMSE dengan model ARIMA (1, 0, 0), dan ARIMA (2, 0, 0), masing-masing sebesar 1, 3738, 1.5514, sedangkan ANN dengan 16 hidden layer sebesar 4.6814. Hasil dari penelitian ini model ARIMA (1, 0, 0) lebih akurat dibandingkan metode ANN dalam prediksi harga saham PT. Bumi Citra Permai Tbk.'),
(7, 'Prediksi Harga Saham menggunakan Metode Recurrent Neural Network', 26, 'M Abdul Dwiyanto Suyudi, Esmeralda C Djamal, Asri Maspupah', 'Saham merupakan salah satu pilihan investasi yang menarik karena dapat diperoleh untung yang besar dibandingkan dengan usaha lainnya. Untuk meminimalkan resiko kerugian, diperlukan perhatian yang jeli terhadap pergerakan saham dan perkembangan pasar modal merupakan salah satu indikator yang perlu dipantau. Dengan teknologi pemrosesan prediksi dan pembelajaran mesin saat ini, identifikasi prediksi harga saham dapat dilakukan secara otomatis. Deep Learning merupakan salah satu bagian dari pembelajaran mesin, dan memiliki akurasi pengenalan yang tinggi dengan data yang sangat banyak. Penelitian ini menggunakan analisis history harga saham dalam suatu perusahaan, dan Recurrent Neural Network (RNN) untuk melakukan prediksi terhadap nilai saham dari history harga saham. Fitur yang diidentifikasi yaitu harga terendah, harga tertinggi, harga buka, harga tutup, volume, rata-rata harga, dan pergerakan. Prediksi tujuh fitur variabel dengan RNN menghasilkan akurasi sebesar 94% untuk data latih dan 55% untuk data uji. Akurasi diperoleh setelah pelatihan dengan menggunakan 1218 data.'),
(8, 'Implementasi Support Vector Machine Pada Prediksi Harga Saham Gabungan (Ihsg)', 25, 'Eka Patriya', 'Saham adalah instrumen pasar keuangan yang banyak dipilih oleh investor sebagai alternatif sumber keuangan, akan tetapi saham yang diperjual belikan di pasar keuangan sering mengalami fluktuasi harga (naik dan turun) yang tinggi. Para investor berpeluang tidak hanya mendapat keuntungan, tetapi juga dapat mengalami kerugian di masa mendatang. Salah satu indikator yang perlu diperhatikan oleh investor dalam berinvestasi saham adalah pergerakan Indeks Harga Saham Gabungan (IHSG). Tindakan dalam menganalisa IHSG merupakan hal yang penting dilakukan oleh investor dengan tujuan untuk menemukan suatu trend atau pola yang mungkin berulang dari pergerakan harga saham masa lalu, sehingga dapat digunakan untuk memprediksi pergerakan harga saham di masa mendatang. Salah satu metode yang dapat digunakan untuk memprediksi pergerakan harga saham secara akurat adalah machine learning. Pada penelitian ini dibuat sebuah model prediksi harga penutupan IHSG menggunakan algoritma Support Vector Regression (SVR) yang menghasilkan kemampuan prediksi dan generalisasi yang baik dengan nilai RMSE training dan testing sebesar 14.334 dan 20.281, serta MAPE training dan testing sebesar 0.211% dan 0.251%. Hasil penelitian ini diharapkan dapat membantu para investor dalam mengambil keputusan untuk menyusun strategi investasi saham.'),
(9, 'Prediksi Harga Saham Menggunakan Jaringan Syaraf Tiruan Backpropagation', 10, 'Siti Amiroch', 'Dalam bursa saham, prediksi harga saham merupakan isu penting bagi pelaku transaksi modal untuk membantu pengambilan keputusan yang tepat. Kebanyakan para trader mempunyai software aplikasi sendiri untuk memprediksi harga saham sehingga bisa diputuskan akan membeli saham tersebut atau bahkan menjualnya. Dengan menggunakan neural network atau jaringan syaraf tiruan, prediksi harga saham bisa dilakukan dengan menggunakan algoritma backpropagation. Jaringan syaraf tiruandapat digunakan baik untuk memprediksi level atau harga indeks saham, pergerakan saham (trend), maupun return yang diperoleh atas saham. Penelitian ini membahas penggunaan teknik Jaringan Syaraf Tiruan Backpropagation untuk memprediksi harga sahampenutupan (Close) pada PT AKR Corporindo Tbk (AKRA Corporindo) yang bergerak di bidang petrolium, chemical, logistik, pabrikan dan batubara yangdisimulasikan dalam matlab. Dari beberapa testing yang dilakukan, diperoleh hasilprediksi sangat mendekati harga sebenarnya dengan nilai MSE yang sangat kecil.'),
(10, 'Prediksi Pergerakan Harga Saham Pada Bank Terbesar Di Indonesia Dengan Metode Backpropagation Neural Network', 24, 'Agnes Novita', 'Prediksi harga saham perusahaan sangatlah penting bagi perusahaan dan para investor untuk menentukan strategi atau pengambilan keputusan bisnis dalam membeli saham suatu perusahaan, dan hal ini disebabkan oleh perubahan harga saham yang dapat terjadi setiap saat. Prediksi harga saham dilakukan dengan melakukan analisa terhadap data-data harga saham pada periode sebelumnya, seperti harga saham pembukaan, harga tertinggi, harga terendah dan harga penutupan sehingga harga saham pada waktu yang akan datang dapat diprediksi. Penelitian ini dilakukan untuk memprediksi harga saham pada bank BRI sebagai bank pemerintah dan BCA sebagai bank swasta yang merupakan bank terbaik berdasarkan modal intinya yang berada di atas 30 triliun Rupiah pada tahun 2013 berdasarkan data dari majalah infobank. Teknik yang digunakan untuk memprediksi harga saham pada penelitian ini menggunakan metode Back Propagation Neural Network Metode ini sangat sesuai untuk data time series yang bersifat non-linier. Data-data yang digunakan adalah data harga saham pada 4 bank terbesar berdasarkan modal intinya yang berjumlah di atas 30 triliun Rupiah, yaitu bank BRI, Mandiri, BNI dan BCA. Data yang digunakan adalah data harga saham harian selama tahun 2013. Hasil penelitian mengenai prediksi harga saham pada bank BRI dan BCA dengan menggunakan metode BPNN ini memiliki nilai akurasi yang baik, di mana hasil yang diperoleh mendekati data yang sebenarnya.'),
(11, 'Metode Neural Network Untuk Penentuan Akurasi Prediksi Harga Rumah', 5, 'Ihda Innar Ridho, Galih Mahalisa, Dwi Retno Sari, Ihsanul Fikri', 'Tempat tinggal atau rumah merupakan salah satu dari banyaknya kebutuhan primer bagi setiap orang khususnya keluarga untuk mendapatkan tempat tinggal pribadi, sehingga pertimbangan dalam pembelian rumah diperlukan sebuah metode yang membantu untuk menentukan harga yang sesuai dengan keinginan pembeli. Neural network adalah model yang terinspirasi oleh bagaimana neuron dalam otak manusia bekerja. Neural Network terdiri dari sejumlah besar elemen pemrosesan informasi (neuron) yang saling terhubung dan bekerja bersama-sama untuk menyelesaikan sebuah masalah tertentu, yang pada umumnya dalah masalah klasifikasi ataupun prediksi. Adapun terkait variabel yang mempengaruhi harga rumah diantaranya luas lahan, banyaknya kamar tidur, dan banyaknya kamar mandi. Dilakukan uji akurasi dan uji kinerja pemodelan dengan hasil adalah 74% untuk skor Akurasi, dan 0, 28 untuk skor MAE.'),
(12, 'Analisis Tren Kepemilikan Rumah di Kota Palembang dan Prediksi Harga Rumah memanfaatkan Machine Learning', 1, 'Kgs Muhammad Benyamin Azhary', 'Perkembangan teknologi sudah cukup pesat dan penggunaan sistem elektronik sudah menjadi lumrah. Semua kegiatan yang dilakukan secara manual dan memakan waktu berubah menjadi cepat dan singkat dengan bantuan aplikasi dan sistem elektronik. Prediksi harga rumah berdasarkan tren dari pemasaran digital merupakan upaya memanfaatkan teknologi digital dan mencoba merangcang aplikasi sederhana yang memudahkan masayarakat dalam merencanakan keuangan untuk memiliki hunian tempat tinggal yang sesuai dengan kebutuhan dan keadaan finansial. Rancangan Prediksi Harga Rumah ini dikembangkan menggunakan aplikasi Python dan memanfaatkan data dari web pemasaran digital. Proses penelitian dilakukan hingga tahap deployment, tahap awal pengumpulan data memanfaatkan fungsi webscraping, lalu proses klastering untuk melihat ketersediaan rumah, menggunakan fungsi decision tree untuk melihat pola pembeli, proses prediksi harga dan faktor yang mempengaruhi berdasarkan hasil regresi, selanjutnya pemetaan tren persebaran rumah untuk melihat secara visual persebaran rumah yang paling diminati, tahap akhir penelitian adalah deployment merupakan rancangan pengembangan untuk melakukan prediksi harga rumah.'),
(13, 'Sistem Pendukung Keputusan Prediksi Harga Rumah Kost untuk Mahasiswa IT Telkom Purwokerto Menggunakan Metode Fuzzy Tsukamoto Berbasis Web', 3, 'Ummi Athiyah, Arnelka Hananta, Taufik Maulidi, Vico Meylana Eka Putra, Theo Felix Harianto Purba, Elisabeth Angeline Wilhelmina Bakowatun', 'Purwokerto City is a developing city located in the southwestern part of Central Java Province. Purwokerto is known as the'),
(14, 'Klasifikasi Citra Buah Menggunakan Convolutional Neural Network', 91, 'Febian Fitra Maulana, Naim Rochmawati', 'Deep Learning merupakan sebuah pengembangan dari teknologi Machine Learning yang menggunakan algoritma yang dibuat berdasarkan pada hukum matematik yang bekerja layaknya otak manusia. Salah satu pemanfaatan dari deep learning adalah dalam bidang image processing atau pengolahan citra digital. Image Processing dimanfaatkan untuk membantu manusia dalam mengenali dan/atau mengklasifikasi objek dengan cepat, tepat, dan dapat melakukan proses dengan banyak data secara bersamaan. Salah Satu algoritma dari Deep learning yang digunakan dalam image processing adalah Convolutional Neural Network (CNN). Algoritma CNN terdiri dari 3 layer utama yaitu Convolutional Layer, Pooling Layer, dan Fully Connected Layer. Pada penelitian ini menggunakan arsitektur CNN dengan perpaduan 3 Convolutional Neural Network dan 2 Fully Connected Layer. Pada tahap pembuatan system klasifikasi yang menggunakan deep learning terdapat beberapa tahapan proses utama yaitu pengumpulan data, perancangan system, training, dan testing. Dataset yang diolah adalah dataset citra buah-buahan yang berasal dari dataset Fruit-360. Kelas data yang digunakan yaitu sejumlah 15 kelas dari 111 kelas pada dataset fruit-360. Hasil dari proses learning didapatkan model CNN dengan akurasi 100% dan loss sebesar 0,012. Pada proses pengujian model CNN yang mengguakan 45 sampel citra buah didapatkan akurasi sebesar 91, 42%. Sehingga dapat disimpulkan bahwa metode CNN yang dirancang pada penelitian ini dapat mengklasifikasi citra dengan baik.'),
(15, 'Klasifikasi citra batik menggunakan jaringan syaraf tiruan berdasarkan gray level co-occurrence matrices (GLCM)', 66, 'Anita Ahmad Kasim, Agus Harjoko', 'Pelestarian Batik dapat dilakukan dengan berbagai cara, salah satunya dengan cara melestarikan pola-pola batik yang sangat beragam di Indonesia. Batik merupakan warisan budaya Indonesia yang telah diakui UNESCO sebagai warisan budaya internasional pada tanggal 2 Oktober 2009. Untuk melestarikan batik sebagai salah satu warisan budaya dunia dapat dilakukan melalui pengenalan pola batik di Indonesia. Salah satu permasalahan dalam bidang pengenalan pola adalah klasifikasi citra ke dalam kelas tertentu. Batik dapat diklasifikasikan berdasarkan bentuk motifnya yaitu motif geometri, motif non geometri dan motif khusus. Motif Citra batik yang sangat beragam menyulitkan dalam pengenalan setiap pola citra batik. Tujuan klasifikasi batik adalah membagi citra batik ke dalam kelas-kelas motif sesuai dengan pola motifnya sehingga mudah untuk dikenali sesuai dengan cirinya. Dengan menggunakan algoritma backpropagatian pada jaringan syaraf tiruan diperoleh hasil untuk kemampuan jaringan syaraf mengklasifikasi citra batik dalam 2 buah kelas non geometri dan geometri sebesar 95.7% pada data latih. Dari 37 (91.9%) ciri citra batik non geometri terdapat 3 (8.1%) ciri yang tidak dapat diklasifikasi kedalam kelasnya. Sedangkan untuk ciri citra geometri semua ciri citra dapat diklasifikasi dengan benar (100%). Untuk proses pengujian terdapat 2 (18.2%) ciri yang tidak bisa diklasifikasi dan pada proses uji validitas semua ciri dapat diklasifikasikan dengan baik.'),
(16, 'Klasifikasi Citra Menggunakan Convolutional Neural Network dan K Fold Cross Validation', 71, 'Ari Peryanto, Anton Yudhana, Rusydi Umar', 'Image classification is a fairly easy task for humans, but for machines it is something that is very complex and is a major problem in the field of Computer Vision which has long been sought for a solution. There are many algorithms used for image classification, one of which is Convolutional Neural Network, which is the development of Multi Layer Perceptron (MLP) and is one of the algorithms of Deep Learning. This method has the most significant results in image recognition, because this method tries to imitate the image recognition system in the human visual cortex, so it has the ability to process image information. In this research the implementation of this method is done by using the Keras library with the Python programming language. The results showed the percentage of accuracy with K= 5 cross-validation obtained the highest level of accuracy of 80.36% and the highest average accuracy of 76.49%, and system accuracy of 72.02%. For the lowest accuracy obtained in the 4th and 5th testing with an accuracy value of 66.07%. The system that has been made has also been able to predict with the highest average prediction of 60.31%, and the highest prediction value of 65.47%.'),
(17, 'Klasifikasi Citra Daun Herbal Dengan Menggunakan Backpropagation Neural Networks Berdasarkan Ekstraksi Ciri Bentuk', 67, 'Arief Herdiansah, Rohmat Indra Borman, Desi Nurnaningsih, Alfry Aristo J Sinlae, Rosyid Ridlo Al Hakim', 'Sejak zaman dahulu hingga sekarang tanaman herbal telah dimanfaatkan untuk pengobatan dan telah diterapkan di dunia kesehatan sampai saat ini. Seluruh bagian tumbuhan dapat digunakan sebagai obat, salah satunya adalah daunnya. Namun, masih banyak orang yang belum mengenal daun herbal daun obat tersebut. Hal ini dikarenakan daun sekilas terlihat hampir sama, sehingga sulit untuk membedakannya. Sebenarnya jika dicermati, daun memiliki ciri-ciri yang dapat dibedakan antara daun satu dengan yang lain. Tujuan penelitian ini yaitu unuk mengklasifikasikan citra jenis daun herbal menggunakan algoritma Backpropagation Neural Network (BNN) dengan ekstraksi ciri bentuk memanfaatkan parameter metric dan eccentricity. BNN merupakan jenis algoritma pembeljaran terawasi yang terdari dari beberapa lapisan dan menggunakan output error sebagai pengubah nilai bobot ke arah belakang. Pada penelitian ini pada ekstraksi ciri bentuk yang menjadi masukan untuk algortima BNN akan melalui operasi morfologi untuk memperbaiki hasil segmentasi agar hasil klasifikasi lebih optimal. Hasil pengujian menunjukkan akurasi sebesar 88, 75%, ini menunjukkan model yang dikembangkan dapat mengklasifikasikan daun herbal dengan baik.'),
(18, 'Klasifikasi citra digital bumbu dan rempah dengan algoritma convolutional neural network (cnn)', 63, 'Isna Wulandari, Hasbi Yasin, Tatik Widiharih', 'The recognition of herbs and spices among young generation is still low. Based on research in SMK 9 Bandung, showed that there are 47% of students that did not recognize herbs and spices. The method that can be used to overcome this problem is automatic digital sorting of herbs and spices using Convolutional Neural Network (CNN) algorithm. In this study, there are 300 images of herbs and spices that will be classified into 3 categories. It&#8217;s ginseng, ginger and galangal. Data in each category is divided into two, training data and testing data with a ratio of 80%: 20%. CNN model used in classification of digital images of herbs and spices is a model with 2 convolutional layers, where the first convolutional layer has 10 filters and the second convolutional layer has 20 filters. Each filter has a kernel matrix with a size of 3x3. The filter size at the pooling layer is 3x3 and the number of neurons in the hidden layer is 10. The activation function at the convolutional layer and hidden layer is tanh, and the activation function at the output layer is softmax. In this model, the accuracy of training data is 0.9875 and the loss value is 0.0769. The accuracy of testing data is 0.85 and the loss value is 0.4773. Meanwhile, testing new data with 3 images for each category produces an accuracy of 88.89%.'),
(19, 'Klasifikasi Citra Jenis Daun Berkhasiat Obat Menggunakan Algoritma Jaringan Syaraf Tiruan Extreme Learning Machine', 72, 'Rhaishudin Jafar Rumandan, Rini Nuraini, Nanang Sadikin, Yuri Rahmanto', 'Abstrak&#8722; Daun adalah salah satu bagian tumbuhan yang mempunyai manfaat bagi manusia khususnya untuk kesehatan tubuh. Daun dapat digunakan sebagai obat herbal yang dapat menjadi alternatif yang dapat membantu dalam meningkatkan imun serta daya tahan tubuh. Akan tetapi tidak semua daun memiliki khasiat sebagai obat, maka dari itu pengetahuan mengenai jenis-jenis daun berkhasiat obat menjadi suatu hal yang penting. Tujuan dari penelitian yaitu untuk mengembangkan sistem klasifikasi citra daun berkhasiat obat dengan menerapkan model jaringan syaraf tiruan Extreme Learning Machine (ELM). Untuk mendukung algoritma ELM digunakan ekstraksi ciri morfologi yang dapat memberikan informasi mengenai karakteristik bentuk dari objek yang ada. Extreme Learning Machine (ELM) disebut juga sebagai pendekatan jaringan syaraf tiruan yang menggunakan satu hidden layer. Pada tahap klasifikasi algoritma Extreme Learning Machine (ELM) dapat menentukan nilai bobot antara input neuron dan hidden layer secara random sehingga pola pembelajaran menjadi lebih cepat. Berdasarkan hasil uji precision, recall dan accuracy menghasilkan nilai precision sebesar 90.67%, nilai recall sebesar 89.47% dan accuracy sebesar 90%. Sehingga, berdasarkan hasil tersebut dapat dikatakan bahwa model ELM yang dibangun dapat mengklasifikasikan citra jenis daun berkhasiat obat dengan baik.'),
(20, 'Klasifikasi Citra Ikan Berformalin Menggunakan Metode K-NN dan GLCM', 37, 'Ayu Pariyandani, Diah Ayu Larasati, Eka Pirdia Wanti, Muhathir Muhathir', 'Pada dasarnya ikan merupakan makanan yang tinggi protein sehingga banyak masyarakat Indonesia mengkonsumsi ikan sebagai asupan protein untuk kesehatannya. Ikan juga tersebar diseluruh perairan Indonesia, hal ini menyebabkan sebagian masyarakat Indonesia berprofesi sebagai nelayan. Hal tersebut membuat jumlah Ikan yang ditangkap juga semakin banyak. Dengan banyaknya jumlah ikan tersebut, banyak para penjual ikan yang mencari cara agar ikan yang belum terjual tidak cepat membusuk. Mungkin ada beberapa penjual yang menggunakan Formalin untuk membuat ikan dagangannya tidak busuk. Oleh karena itu dibuat system untuk mengenali ikan yang segar dengan ikan yang berformalin dengan menggunakan metode GLCM dan K-NN. Dengan menggunakan metode ini kita dapat mengenali ikan segar sebagai ikan segar sebesar 53% dan ikan berformalin dikenali sebagai ikan yang berformalin sebesar 92%.'),
(21, 'Prediksi Tingkat Produksi Kopi Menggunakan Regresi Linear', 110, 'Petrus Katemba, Rosita Koro Djoh', 'Kabupaten Manggarai menjadi sentra produksi kopi di Nusa Tenggara Timur, yang dikenal dengan sebutan &#8220;Kopi Tuan&#8221;. Kopi dari daerah ini menjadi andalan ekspor hasil perkebunan, yang telah menembus pasar internasional dengan harga tinggi karena mutunya yang baik. Namun produksi kopi cenderung menurun yang mengakibatkan permintaan akan kopi mengalami penurunan yang disebabkan oleh beberapa faktor, baik faktor alam dan sistem yang digunakan masih tradisional. Upaya peningkatan produksi kopi telah dilakukan pemerintah dengan berbagai cara, namun lemahnya teknologi pendukung menjadi salah satu kendala peningkatan produksi kopi. Tujuan yang ingin dicapai adalah untuk mengetahuai apakah produksi kopi mengalami peningkatan atau penurunan dari waktu ke waktu. Untuk memenuhi kebutuhan kopi maka dilakukan prediksi dengan menggunakan Regresi linear sederhana atau Simple Regresi Linear yang merupakan salah satu metode statistik yang dipergunakan dalam produksi untuk melakukan peramalan ataupun prediksi tentang karakteristik kualitas maupun kuantitas. Simple Regresi Linear terdiri dari satu buah variabel bebas (x) dengan satu buah variabel terikat (y). Dengan melakukan prediksi menggunakan Metode Regresi Linear dapat memberikan informasi yang membantu para petani dan pemerintah dalam mengambil kebijakan guna meningkatkan produksi kopi di Kabupaten Manggarai. Hasil yang diperoleh dari penelitian ini yang melibatkan 5 periode yaitu dari tahun 2011-2015 nilai tertinggi pada tahun 2015 sebesar 1.537, 38 ton dan nilai terendah pada tahun 2011 sebesar 1.109?&#8230;'),
(22, 'Analisis prediksi indeks harga konsumen berdasarkan kelompok kesehatan dengan menggunakan metode backpropagation', 150, 'Anjar Wanto, Agus Perdana Windarto', 'Analisis pada sebuah prediksi (peramalan) sangat penting dilakukan pada sebuah penelitian, agar penelitian menjadi lebih tepat dan terarah. Seperti halnya dalam memprediksi Indeks Harga Konsumen berdasarkan kelompok kesehatan, diperlukan adanya kajian-kajian dan penggunaan metode yang tepat untuk mendapatkan hasil yang optimal. Penelitian ini diharapkan dapat bermanfaat secara luas, baik bagi Pemerintah Daerah maupun pihak swasta sebagai salah satu bahan kajian dalam pengembangan bisnis, maupun bagi para akademisi sebagai bahan kajian/penelitian khususnya yang terkait dengan bidang ekonomi dan kebijakan publik. Data yang digunakan dalam penelitian ini adalah data Indeks Harga Konsumen berdasarkan kelompok Kesehatan yang berasal dari Badan Pusat Statistik Kota Medan dari tahun 2014 sampai dengan tahun 2016, bulan Januari sampai dengan Desember. Penelitian ini menggunakan metode jaringan saraf tiruan Backpropagation dengan menggunakan 8 model arsitektur, yakni: 12-5-1, 12-26-1, 12-29-1, 12-35-1, 12-40-1, 12-60-1, 12-70-1 dan 12-75-1. Penggunaan metode ini nantinya akan menghasilkan prediksi dengan tingkat akurasi sebesar 92% dan besar MSE 0, 3659742 dengan tingkat error yang digunakan 0,001&#8211;0, 05 dengan menggunakan model arsitektur 12-70-1. Dengan demikian, model ini cukup bagus untuk prediksi Indeks Harga Konsumen berdasarkan kelompok kesehatan.'),
(23, 'Analisa Prediksi Pertumbuhan Start-up Di Era Industri 4.0 Menggunakan Metode Markov Chain', 265, 'Taufik Hidayat, Dewi Yunita Sari, Yasep Azzery', 'Bisnis Start-up semakin tumbuh dan berkembang di berbagai daerah di Indonesia, tidak terkecuali di Jabodetabek. Dari bisnis Start-up dapat menghasilkan berbagai platform atau aplikasi yang diminati konsumen, seperti marketplace pada E-commerce. Jabodetabek merupakan daerah dengan tingkat pertumbuhan Start-up tertinggi sebanyak 522 Start-up, yang mayoritas berasal dari kota Jakarta. Penggunaan metode Markov chain untuk memprediksi pertumbuhan dengan melakukan perhitungan matriks transisi probabilitas, serta menghitung probabilitas keadaan sampai diperoleh keadaan Steady state yang merupakan data acuan untuk hasil prediksi pertumbuhan Start-up di Jabodetabek di 5 tahun berikutnya.'),
(24, 'Penerapan Algoritma C4. 5 pada Aplikasi Prediksi Kelulusan Mahasiswa Prodi Informatika', 54, 'Ratna Puspita Sari Putri, Indra Waspada', 'Data tentang mahasiswa yang lulus merupakan sebuah data yang penting baik bagi departemen, fakultas maupun universitas karena data tersebut digunakan dalam proses akreditasi. Data tentang mahasiswa yang lulus terus bertambah di tiap tahunnya dan menumpuk seperti data yang terabaikan karena jarang digunakan. Data tentang mahasiswa yang lulus dapat memberikan informasi yang berguna jika dimanfaatkan dengan maksimal. Maka dari itu, penelitian ini akan memanfaatkan data tentang mahasiswa yang lulus dengan mengolahnya menggunakan data mining untuk mendapatkan informasi berupa prediksi kelulusan mahasiswa. Metode yang akan digunakan adalah metode pohon keputusan yang dibangun dengan algoritma C4. 5 disertai dengan algoritma error-based pruning untuk proses pemotongan pohon keputusan. Kriteria yang akan digunakan adalah jenis kelamin, asal daerah, IPK, dan TOEFL. Dalam penerapannya, algoritma C4. 5 dapat digunakan untuk menghasilkan prediksi kelulusan dengan nilai rata-rata precision 63.93%, recall 60.73%, dan akurasi 60.52%. Setelah pohon keputusan dipotong dengan menggunakan metode error-based pruning, didapatkan hasil yang lebih baik. Pohon yang dipotong dengan menggunakan nilai confidence 0, 4 menghasilkan precision 70.70%, recall 50.65%, dan akurasi 61.57%. Sedangkan pohon yang dipotong dengan menggunakan nilai confidence 0, 25 menghasilkan precision 73.77%, recall 48.84%, dan akurasi 62.44%.'),
(25, 'Prediksi Financial Distress pada Perusahaan Manufaktur di Bursa Efek Indonesia', 148, 'Randy Kurnia Permana, Nurmala Ahmar, Syahril Djadang', 'Penelitian ini bertujuan untuk mengetahui, menganalisis, membuktikan dan menguji perbedaan hasil status kesehatan antara model Grover, Springate, dan Zmijewski. Model tersebut digunakan oleh investor yang akan menanamkan modalnya di perusahaan. Data penelitian diuji menggunakan uji chi square. Hasil penelitian menunjukkan hipotesis 1 diterima yaitu terdapat perbedaan status kesehatan pada pengujian model Grover, Springate, dan Zmijewski pada perusahan manufaktur yang terdaftar di BEI tahun 2006-2015. Model Springate merupakan model prediksi terbaik dibandingkan model Grover dan Springate, karena mempunyai komponen lebih banyak dari kedua model lainnya dan model Springate mempunyai komponen EBIT To Current Liabilities yaitu seberapa besar kemampuan laba dalam membayar hutang perusahaan. Komponen ini adalah komponen yang sangat penting untuk melihat kesulitan keuangan, karena kesulitan keuangan salah satunya terjadi karena hutang yang tidak tercakup oleh perusahaan.'),
(26, 'Prediksi Risiko Investasi Saham', 80, 'Zarah Puspitaningtyas', 'Buku, dengan judul Prediksi Risiko Investasi Saham: Decision Usefulness Approach ini mencoba mengangkat isu yang berkaitan dengan risiko dalam berinvestasi pada saham di Bursa Efek Indonesia. Secara lebih khusus, buku ini mengangkat isu faktor-faktor penentu return saham dengan penekanan pada faktor akuntansi. Dengan kata lain, buku ini sebenarnya merupakan salah satu buku yang mengangkat isu kemampuan faktor-faktor fundamental dalam menjelaskan variasi return atau imbal hasil saham dengan sampel penelitian adalah perusahaan yang tergolong ke dalam sektor real-estate dan property yang listed di Bursa Efek Indonesia. Publikasi buku yang berbasis pada hasil penelitian yang berbentuk buku teks atau buku referensi relatif masih jarang di Indonesia. Buku ini diharapkan mampu mengisi kekosongan tersebut. Buku ini murni berbasis empiris dengan kajian yang cukup komprehensif khususnya terkait dengan sumber referensi yang digunakan, dimana penulis mampu mengkombinasikan sumber referensi berbasis publikasi artikel di jurnal dan sumber referensi lain. Hal ini menunjukkan kematangan akademik penulis. Buku ini memiliki beberapa hal yang menarik untuk dikomentari. Pertama, buku ini ditulis dengan gaya bahasa akademik dengan berbagai istilah statistik yang kental, dimana pembaca akan banyak menemui beberapa istilah statistik, seperti signifi kan, tingkat signifi kansi, pengaruh, atau hipotesis.'),
(27, 'Optimalisasi model prediksi kesesuaian lahan kelapa sawit menggunakan algoritme pohon keputusan spasial', 142, 'Andi Nurkholis, Imas Sukaesih Sitanggang', 'Evaluasi kesesuaian lahan memiliki peran penting dalam perencanaan penggunaan lahan yang bertujuan meningkatkan efektifitas produksi pangan. Komoditas kelapa sawit merupakan komoditas unggulan dan strategis bagi masyarakat Indonesia yang di masa depan diprediksi jumlah konsumsinya akan melebihi jumlah produksi. Penelitian ini bertujuan untuk mengevaluasi kesesuaian lahan kelapa sawit menggunakan algoritme pohon keputusan spasial yang merupakan modifikasi algoritme pohon keputusan konvensional untuk klasifikasi data spasial dengan penambahan berupa spatial join relation. Dataset spasial terdiri dari lapis penjelas (sifat dan karakteristik tanah) dan lapis target (kesesuaian lahan kelapa sawit) pada wilayah studi Kabupaten Bogor, Indonesia. Penelitian ini menghasilkan tiga model, dimana model terbaik diperoleh berdasarkan hasil optimalisasi akurasi (98, 18%) dan waktu pembuatan model (1,291 detik). Pohon keputusan terbaik memiliki 23 aturan, tekstur tanah sebagai node akar, dua variabel (drainase dan kapasitas tukar kation) tidak terlibat, dan pemetaan kesesuaian lahan memperoleh persentase S2 (29, 94%), S3 (53, 16%), N (16, 57%), dan tubuh air (0, 33%).'),
(28, 'Rasio keuangan dan prediksi financial distress', 95, 'Jenny Pratiwi Assaji, Zaky Machmuddah', 'Tujuan dari penelitian ini adalah untuk memahami pengaruh rasio keuangan dalam memprediksi kemungkinan terjadinya financial distress pada perusahaan yang terdaftar pada indeks Sri Kehati secara berturut-turut tahun 2009-2016. Penelitian ini menggunakan rasio keuangan yang diproksikan dengan pengembalian atas aset, pengembalian atas modal, marjin laba bersih, rasio P/E, dan perputaran aset sebagai variabel bebas. Sedangkan, financial distress yang diproksikan dengan Z-score merupakan variabel terikat. Populasi penelitian ini adalah seluruh perusahaan yang terdaftar pada indeks Sri Kehati tahun 2009-2016 dan tercatat pada Bursa Efek Indonesia. Sampel penelitian ini mengambil sembilan perusahaan dengan metode purposive sampling dan periode penelitian adalah selama delapan tahun berturut-turut (2009-2016). Metode penelitian ini menggnakan regresi logistik. Hasil penelitian menunjukkan bahwa ROA, ROE dan PER memberikan pengaruh yang sifnifikan terhadap financial distress. Sedangkan, NPM dan ATO tidak memberikan pengaruh yang signifikan terhadap financial distress.'),
(29, 'Aplikasi prediksi jumlah kebutuhan perusahaan', 36, 'Roni Habibi, Alwan Suryansah', 'Buku ini membahas tentang pengguaan Prediksi kebutuhan sebuah perusahaan kedepannya yang harus diusahakan, dengan begitu akan memudahkan atasan untuk mengambil sebuah keputusan, dengan menggunakan metode Moving Average untuk perhitungan Prediksi. Dalam buku ini membahas juga tentang teori teori dan pengertian pengertian yang dibahas dalam buku ini');

--
-- Indexes for dumped tables
--

--
-- Indeks untuk tabel `articles`
--
ALTER TABLE `articles`
  ADD PRIMARY KEY (`id`),
  ADD UNIQUE KEY `id` (`id`);

--
-- AUTO_INCREMENT untuk tabel yang dibuang
--

--
-- AUTO_INCREMENT untuk tabel `articles`
--
ALTER TABLE `articles`
  MODIFY `id` bigint(20) UNSIGNED NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=30;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
